language: ruby
rvm:
 - "1.8.7"

install:
    - pip install dogesay 
    - gem install cowsay

script: 
    - dogesay "python" "pip" "packages"
    - cowsay "gems"
    - python test.py
    - ruby test.rb
