language: ruby

rvm: 
 - "2.1"
 - "2.2"

install:
    - pip install --user pysay
    - gem install cowsay
    - export PATH=$PATH:~/.local/bin/

script: 
    - pysay "pip"
    - python test.py
    - python --version
    - cowsay "gems"
    - ruby test.rb
    - ruby --version
