language: ruby

rvm: 
 - "2.1"
 - "2.2"

install:
    - pip install --user pysay
    - gem install cowsay
    - export PATH=$PATH:~/.local/bin/
    - wget https://gist.githubusercontent.com/edunham/6ee5b97100bf4b77d3a1/raw/0b211ce0505398767387daf36d4aa85d26e559fb/ferris.cow

script: 
    - pysay -f ~/ferris "pip"
    - python test.py
    - python --version
    - cowsay "gems"
    - ruby test.rb
    - ruby --version
