language: python 
sudo: false
python:
 - "2.7"
 - "3.0"

install:
    - pip install pysay
    - gem install cowsay

script: 
    - pysay "pip"
    - python test.py
    - python --version
    - python3 --version
    - cowsay "gems"
    - ruby test.rb
    - ruby --version
