language: ruby

rvm: 
 - "2.1"
 - "2.2"

install:
    - sudo pip install pysay
    - gem install cowsay

script: 
    - pysay "pip"
    - python test.py
    - python --version
    - cowsay "gems"
    - ruby test.rb
    - ruby --version
