language: ruby

rvm:
 - "1.8.7"
 - "2.0.0"

install:
    - sudo pip install pysay
    - gem install cowsay

script: 
    - pysay "pip"
    - python test.py
    - python --version
    - python3 --version
    - cowsay "gems"
    - ruby test.rb
    - ruby --version
